export const seedCategories: { slug: string; name: string; topics: string[] }[] = [
  {
    slug: "interview",
    name: "Interview",
    topics: [
      "Tell me about yourself.",
      "Why do you want this role?",
      "What is your greatest strength, and how has it helped you at work?",
      "Describe a time you failed and what you learned from it.",
      "Tell me about a time you disagreed with a colleague and how you resolved it.",
      "Where do you see yourself in five years?",
      "Why should we hire you over other candidates?",
      "Describe a project you are proud of.",
      "How do you handle tight deadlines and competing priorities?",
      "Tell me about a time you led a team through a difficult situation.",
    ],
  },
  {
    slug: "everyday",
    name: "Everyday life",
    topics: [
      "Describe your perfect weekend.",
      "What is the best meal you have ever had?",
      "Explain how to make your favourite dish.",
      "Describe your commute or the way you usually get around.",
      "What does your ideal home look like?",
      "Talk about a hobby you enjoy and why.",
      "Describe a place you would love to visit and why.",
      "What is a small thing that reliably makes your day better?",
    ],
  },
  {
    slug: "opinion",
    name: "Opinion",
    topics: [
      "Should everyone learn to code?",
      "Is remote work better than working in an office?",
      "Do social media platforms do more harm than good?",
      "Should university education be free?",
      "Is it better to rent or to buy a home?",
      "Should schools ban smartphones?",
      "Is a four-day working week a good idea?",
      "Are people becoming too dependent on technology?",
    ],
  },
  {
    slug: "storytelling",
    name: "Storytelling",
    topics: [
      "Tell the story of the most memorable trip you have taken.",
      "Describe a time you were completely lost.",
      "Tell a story about a teacher who influenced you.",
      "Describe the best gift you have ever given or received.",
      "Tell the story of a time you surprised yourself.",
      "Describe an unexpected encounter with a stranger.",
      "Tell a story about a mistake that turned out well.",
    ],
  },
  {
    slug: "work",
    name: "Work & presentations",
    topics: [
      "Give a one-minute pitch for a product you use every day.",
      "Explain what you do for a living to a ten-year-old.",
      "Present a recent success to your team.",
      "Give a short update on a project that is behind schedule.",
      "Introduce yourself to a new team on your first day.",
      "Explain a complex idea from your field in plain language.",
      "Persuade your manager to approve a new tool or process.",
      "Give a toast at a colleague's farewell.",
    ],
  },
];
